### ISSUE TITLE
Migrate away from Stratus dependency

### ISSUE THREAD

**Issue by MattMcAdams** [UAB-IT/linear#129]
I'm opening a ticket here so I can stay in the loop on how this is going. Jeremy and I met on Zoom the other week and talked about the general history and setup of the project.

One of the priority items is to make a move away from my now unmaintained SCSS toolkit for design systems, [Stratus](https://github.com/MattMcAdams/stratus). A few of the reasons I've decided to take the project down are that I think it was a bit over-engineered for what it does - a great thing for learning, not so great to be used in production. I also want to free up the Stratus namespace on NPM for a future project with a more narrow scope.

I created PR #127 back in September and archived my Stratus repository. The Repo remains public, but the documentation for it is no longer live and I plan to decommission the project altogether by 2022. I'm happy to talk about that project or Linear on a more technical level if needed.

Let me know if there is anything I can do to help, and keep me updated. When this issue has been resolved, I'd appreciate it if you would [release a new version](https://github.com/UAB-IT/linear/blob/master/.github/CONTRIBUTING.md#releasing-a-new-build) so I'll know its officially wrapped up before officially closing this ticket.

**Comment by MattMcAdams** [comment]
As an aside, Stratus is tied into a larger method of token & pattern management that could probably be refactored to be simpler. Refactors are a tough sell to leadership, but it can make things easier to work with and understand. I'm not open to doing refactor work on this, but I'd be happy to share my thoughts if its something you're interested in taking on down the road.

As an aside to the aside, I'm still listed as an owner of many of the UABIT repos. It would probably be best to convert me to an outside contributor and reassign permissions as needed. I believe that is how Tyler is set up. I'm no longer at UAB, but this is an open source project I've contributed to, so never feel like you're bothering me by reaching out or asking questions / advice about it.

**Comment by jgordini** [comment]
Thanks Matt. Frankly your input has been vital to move this request as far as it's gone so far and I really appreciate it. I was successful in compiling and testing the pull request you made earlier. I diff'ed it against the existing CSS as well as running it through W3C's css checker. Both tests passed and I have merged it into the master branch. 

Refactoring is something I would like to take on both to improve the project and extend my own knowledge. I'm not sure when I would have time to start that, probably after annual report, so sometime next year. 

I won't pretend that my github or sass knowledge is on par with yours. So I was planning on leaving you as owner, for the time being. In case I F something up and break the internet. I can definitely move you to outside contributor as well. I'll leave it to you as far as which one you prefer. 

I did fork stratus to the UAB/IT github account. So if it is deleted I can still work on it.  

This will be the first time I have released a new version on github. So it may be a sec before this is done as I am not sure what documentation needs to be done on my end outside of the logs. 

Thanks again for supporting this transition. I'm sorry my familiarity and expertise is not greater in this area. I will do my best to support and maintain this project and see it as both a learning opportunity and a great resource to make my job easier. I will definitely reach out again in the future and appreciate all the work that went into creating this project.

**Comment by MattMcAdams** [comment]
No problem! I'm glad that PR worked well. I know its been a lot to take in and you've been great. I'm sure you'll find your footing and rhythm in no time. I don't mind staying as an owner for now, but plan to make that shift sometime early 2022.

I think for a new version, you'll bump the version number in these files to 1.1.9:
- https://github.com/UAB-IT/linear/blob/master/package.json
- https://github.com/UAB-IT/linear/blob/master/package-lock.json
- https://github.com/UAB-IT/linear/blob/master/src/scss/01-core/_meta.scss

I know you'll have to change it manually in _meta.scss, but there's also an npm command to bump the version in both package files that's technically the "correct" way to do it. (I've always done it manually though)

After the version number has been updated in the files, head over to https://github.com/UAB-IT/linear/releases and "draft a new release" using the other releases as a guide. Drag and drop the built css and js files into the binaries box and you should be good to hit "publish release"

I'd be happy to run through that on zoom if needed, and it might be a good idea to update the directions in contributing.md with that information for future reference.


No rush on this by the way, I know you're probably working on other things, and starting a new job is a lot to take in too.

**Comment by jgordini** [comment]
Thanks Matt! Yeah I was wondering about increasing the version. 
This is great. I'll try to get to this next week. 
Might have a follow up question once I get into it. 

Looks like npm update might do what I need. But I'll do more research before attempting.

**Comment by jgordini** [comment]
Moved you over to outside collaborator.  If there's any issue I can move you back. Haven't had a chance to look at creating the new release but will look at it this week or early next week.

**Comment by jgordini** [comment]
Released version 1.1.9 no longer dependent on Stratus. Sorry about the delay. Thanks again for all your help.
